name: newsblog_prokit
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Base
  cupertino_icons: ^1.0.4
  nb_utils: ^4.4.10
  intl: ^0.17.0
  flutter_vector_icons: ^1.0.0
  google_fonts: ^6.0.0
  mobx: ^2.0.3
  flutter_mobx: ^2.0.1

  #News Blog
  cached_network_image: ^3.1.0
  url_launcher: ^6.0.3
  image_picker: ^0.8.1+3
  path_drawing: ^0.5.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.5+2
  build_runner: ^2.1.7
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:

  uses-material-design: true
  assets:
    - images/
